language: node_js
os: linux
node_js:
  - "14"
jobs:
  include:
      before_deploy:
      - npm test
      deploy:
        edge: true
        provider: npm
        email: "$npm_EMAIL"
        api_key: "$npm_TOKEN"
        cleanup: true
        on:
          branch: main