version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  test_and_publish:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN"
      - run:
          name: Publish package
          command: npm publish          



workflows:
  puppeteer_test:
    jobs:
      - test_and_publish
