  
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      # store test results
      - store_test_results:
          path: test_results

      # store code coverage
      - persist_to_workspace:
          root: ~/repo
          paths: .

      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public
         


workflows:
  build-and-publish:
    jobs:
      - build
